name: Deploy Webhook Dispatcher to GHCR

on:
  push:
    branches:
      - main
    paths:
      - apps/webhook-dispatcher/**
  workflow_dispatch:

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './apps/webhook-dispatcher'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Push Image'
        uses: docker/build-push-action@v6
        with:
          context: ./apps/webhook-dispatcher
          push: true
          tags: ghcr.io/firecrawl/webhook-dispatcher:latest
          cache-from: type=registry,ref=ghcr.io/firecrawl/webhook-dispatcher:buildcache
          cache-to: type=registry,ref=ghcr.io/firecrawl/webhook-dispatcher:buildcache,mode=max
